import Head from 'next/head'

function PageHead() {
  return (
    <Head>
      <title>RainbowKit App</title>
      <meta
        content="Generated by @rainbow-me/create-rainbowkit"
        name="description"
      />
      <link href="/favicon.ico" rel="icon" />
    </Head>
  )
}

export default PageHead
